<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['country_name' => 'AFGHANISTAN', 'country_code' => '308', 'currency_id' => null],
            ['country_name' => 'ALBANIA', 'country_code' => '518', 'currency_id' => null],
            ['country_name' => 'ALEMANIA', 'country_code' => '563', 'currency_id' => null],
            ['country_name' => 'ANDORRA', 'country_code' => '525', 'currency_id' => null],
            ['country_name' => 'ANGOLA', 'country_code' => '140', 'currency_id' => null],
            ['country_name' => 'ANGUILA', 'country_code' => '242', 'currency_id' => null],
            ['country_name' => 'ANTIGUA Y BBUDA', 'country_code' => '240', 'currency_id' => null],
            ['country_name' => 'ANTILLAS NEERLA', 'country_code' => '247', 'currency_id' => null],
            ['country_name' => 'ARABIA SAUDITA', 'country_code' => '302', 'currency_id' => null],
            ['country_name' => 'ARGELIA', 'country_code' => '127', 'currency_id' => null],
            ['country_name' => 'ARGENTINA', 'country_code' => '224', 'currency_id' => null],
            ['country_name' => 'ARMENIA', 'country_code' => '540', 'currency_id' => null],
            ['country_name' => 'ARUBA', 'country_code' => '243', 'currency_id' => null],
            ['country_name' => 'AUSTRALIA', 'country_code' => '406', 'currency_id' => null],
            ['country_name' => 'AUSTRIA', 'country_code' => '509', 'currency_id' => null],
            ['country_name' => 'AZERBAIJAN', 'country_code' => '541', 'currency_id' => null],
            ['country_name' => 'BAHAMAS', 'country_code' => '207', 'currency_id' => null],
            ['country_name' => 'BAHREIN', 'country_code' => '313', 'currency_id' => null],
            ['country_name' => 'BANGLADESH', 'country_code' => '321', 'currency_id' => null],
            ['country_name' => 'BARBADOS', 'country_code' => '204', 'currency_id' => null],
            ['country_name' => 'BELARUS', 'country_code' => '542', 'currency_id' => null],
            ['country_name' => 'BELAU', 'country_code' => '420', 'currency_id' => null],
            ['country_name' => 'BELGICA', 'country_code' => '514', 'currency_id' => null],
            ['country_name' => 'BELICE', 'country_code' => '236', 'currency_id' => null],
            ['country_name' => 'BENIN', 'country_code' => '150', 'currency_id' => null],
            ['country_name' => 'BERMUDAS', 'country_code' => '244', 'currency_id' => null],
            ['country_name' => 'BOLIVIA', 'country_code' => '221', 'currency_id' => null],
            ['country_name' => 'BOSNIA HEZGVINA', 'country_code' => '543', 'currency_id' => null],
            ['country_name' => 'BOTSWANA', 'country_code' => '113', 'currency_id' => null],
            ['country_name' => 'BRASIL', 'country_code' => '220', 'currency_id' => null],
            ['country_name' => 'BRUNEI', 'country_code' => '344', 'currency_id' => null],
            ['country_name' => 'BULGARIA', 'country_code' => '527', 'currency_id' => null],
            ['country_name' => 'BURKINA FASO', 'country_code' => '161', 'currency_id' => null],
            ['country_name' => 'BURUNDI', 'country_code' => '141', 'currency_id' => null],
            ['country_name' => 'BUTAN', 'country_code' => '318', 'currency_id' => null],
            ['country_name' => 'CABO VERDE', 'country_code' => '129', 'currency_id' => null],
            ['country_name' => 'CAMBODIA', 'country_code' => '315', 'currency_id' => null],
            ['country_name' => 'CAMERUN', 'country_code' => '149', 'currency_id' => null],
            ['country_name' => 'CANADA', 'country_code' => '226', 'currency_id' => null],
            ['country_name' => 'CHAD', 'country_code' => '130', 'currency_id' => null],
            ['country_name' => 'CHILE', 'country_code' => '997', 'currency_id' => null, 'is_active' => false], // Disabled
            ['country_name' => 'CHINA', 'country_code' => '336', 'currency_id' => null],
            ['country_name' => 'CHIPRE', 'country_code' => '305', 'currency_id' => null],
            ['country_name' => 'COLOMBIA', 'country_code' => '202', 'currency_id' => null],
            ['country_name' => 'COMB.Y LUBRIC.', 'country_code' => '901', 'currency_id' => null],
            ['country_name' => 'COMORAS', 'country_code' => '118', 'currency_id' => null],
            ['country_name' => 'CONGO', 'country_code' => '144', 'currency_id' => null],
            ['country_name' => 'COREA DEL SUR', 'country_code' => '333', 'currency_id' => null],
            ['country_name' => 'COSTA DE MARFIL', 'country_code' => '107', 'currency_id' => null],
            ['country_name' => 'COSTA RICA', 'country_code' => '211', 'currency_id' => null],
            ['country_name' => 'CROACIA', 'country_code' => '547', 'currency_id' => null],
            ['country_name' => 'CUBA', 'country_code' => '209', 'currency_id' => null],
            ['country_name' => 'DEPOSITO FRANCO', 'country_code' => '906', 'currency_id' => null],
            ['country_name' => 'DINAMARCA', 'country_code' => '507', 'currency_id' => null],
            ['country_name' => 'DJIBOUTI', 'country_code' => '155', 'currency_id' => null],
            ['country_name' => 'DOMINICA', 'country_code' => '231', 'currency_id' => null],
            ['country_name' => 'ECUADOR', 'country_code' => '218', 'currency_id' => null],
            ['country_name' => 'EGIPTO', 'country_code' => '124', 'currency_id' => null],
            ['country_name' => 'EL SALVADOR', 'country_code' => '213', 'currency_id' => null],
            ['country_name' => 'EMIR.ARAB.UNID.', 'country_code' => '341', 'currency_id' => null],
            ['country_name' => 'ERITREA', 'country_code' => '163', 'currency_id' => null],
            ['country_name' => 'ESLOVENIA', 'country_code' => '548', 'currency_id' => null],
            ['country_name' => 'ESPANA', 'country_code' => '517', 'currency_id' => null],
            ['country_name' => 'ESTONIA (B)', 'country_code' => '549', 'currency_id' => null],
            ['country_name' => 'ETIOPIA', 'country_code' => '139', 'currency_id' => null],
            ['country_name' => 'FIJI', 'country_code' => '401', 'currency_id' => null],
            ['country_name' => 'FILIPINAS', 'country_code' => '335', 'currency_id' => null],
            ['country_name' => 'FINLANDIA', 'country_code' => '512', 'currency_id' => null],
            ['country_name' => 'FRANCIA', 'country_code' => '505', 'currency_id' => null],
            ['country_name' => 'GABON', 'country_code' => '145', 'currency_id' => null],
            ['country_name' => 'GAMBIA', 'country_code' => '102', 'currency_id' => null],
            ['country_name' => 'GEORGIA (B)', 'country_code' => '550', 'currency_id' => null],
            ['country_name' => 'GHANA', 'country_code' => '108', 'currency_id' => null],
            ['country_name' => 'GIBRALTAR', 'country_code' => '565', 'currency_id' => null],
            ['country_name' => 'GRANADA', 'country_code' => '232', 'currency_id' => null],
            ['country_name' => 'GRECIA', 'country_code' => '520', 'currency_id' => null],
            ['country_name' => 'GROENLADIA', 'country_code' => '253', 'currency_id' => null],
            ['country_name' => 'GUAM', 'country_code' => '425', 'currency_id' => null],
            ['country_name' => 'GUATEMALA', 'country_code' => '215', 'currency_id' => null],
            ['country_name' => 'GUERNSEY', 'country_code' => '566', 'currency_id' => null],
            ['country_name' => 'GUINEA', 'country_code' => '104', 'currency_id' => null],
            ['country_name' => 'GUINEA ECUATRL', 'country_code' => '147', 'currency_id' => null],
            ['country_name' => 'GUINEA-BISSAU', 'country_code' => '103', 'currency_id' => null],
            ['country_name' => 'GUYANA', 'country_code' => '217', 'currency_id' => null],
            ['country_name' => 'HAITI', 'country_code' => '208', 'currency_id' => null],
            ['country_name' => 'HOLANDA', 'country_code' => '515', 'currency_id' => null],
            ['country_name' => 'HONDURAS', 'country_code' => '214', 'currency_id' => null],
            ['country_name' => 'HONG KONG', 'country_code' => '342', 'currency_id' => null],
            ['country_name' => 'HUNGRIA', 'country_code' => '530', 'currency_id' => null],
            ['country_name' => 'INDIA', 'country_code' => '317', 'currency_id' => null],
            ['country_name' => 'INDONESIA', 'country_code' => '328', 'currency_id' => null],
            ['country_name' => 'IRAK', 'country_code' => '307', 'currency_id' => null],
            ['country_name' => 'IRAN', 'country_code' => '309', 'currency_id' => null],
            ['country_name' => 'IRLANDA', 'country_code' => '506', 'currency_id' => null],
            ['country_name' => 'ISLANDIA', 'country_code' => '516', 'currency_id' => null],
            ['country_name' => 'ISLAS CAYMAN', 'country_code' => '246', 'currency_id' => null],
            ['country_name' => 'ISLAS COOK', 'country_code' => '427', 'currency_id' => null],
            ['country_name' => 'ISLAS DE MAN', 'country_code' => '567', 'currency_id' => null],
            ['country_name' => 'ISLAS MALDIVAS', 'country_code' => '327', 'currency_id' => null],
            ['country_name' => 'ISLAS MARIANAS', 'country_code' => '424', 'currency_id' => null],
            ['country_name' => 'ISLAS MARSHALL', 'country_code' => '164', 'currency_id' => null],
            ['country_name' => 'ISLAS SALOMON', 'country_code' => '418', 'currency_id' => null],
            ['country_name' => 'ISLAS TONGA', 'country_code' => '403', 'currency_id' => null],
            ['country_name' => 'ISLAS VIRG.BRIT', 'country_code' => '245', 'currency_id' => null],
            ['country_name' => 'ISLAS VIRG.EUA', 'country_code' => '249', 'currency_id' => null],
            ['country_name' => 'ISRAEL', 'country_code' => '306', 'currency_id' => null],
            ['country_name' => 'ITALIA', 'country_code' => '504', 'currency_id' => null],
            ['country_name' => 'JAMAICA', 'country_code' => '205', 'currency_id' => null],
            ['country_name' => 'JAPON', 'country_code' => '331', 'currency_id' => null],
            ['country_name' => 'JERSEY', 'country_code' => '568', 'currency_id' => null],
            ['country_name' => 'JORDANIA', 'country_code' => '301', 'currency_id' => null],
            ['country_name' => 'KASAJSTAN', 'country_code' => '551', 'currency_id' => null],
            ['country_name' => 'KENIA', 'country_code' => '137', 'currency_id' => null],
            ['country_name' => 'KIRGISTAN', 'country_code' => '552', 'currency_id' => null],
            ['country_name' => 'KIRIBATI', 'country_code' => '416', 'currency_id' => null],
            ['country_name' => 'KUWAIT', 'country_code' => '303', 'currency_id' => null],
            ['country_name' => 'LAOS', 'country_code' => '316', 'currency_id' => null],
            ['country_name' => 'LESOTHO', 'country_code' => '114', 'currency_id' => null],
            ['country_name' => 'LETONIA', 'country_code' => '553', 'currency_id' => null],
            ['country_name' => 'LIBANO', 'country_code' => '311', 'currency_id' => null],
            ['country_name' => 'LIBERIA', 'country_code' => '106', 'currency_id' => null],
            ['country_name' => 'LIBIA', 'country_code' => '125', 'currency_id' => null],
            ['country_name' => 'LIECHTENSTEIN', 'country_code' => '534', 'currency_id' => null],
            ['country_name' => 'LITUANIA', 'country_code' => '554', 'currency_id' => null],
            ['country_name' => 'LUXEMBURGO', 'country_code' => '532', 'currency_id' => null],
            ['country_name' => 'MACAO', 'country_code' => '345', 'currency_id' => null],
            ['country_name' => 'MACEDONIA', 'country_code' => '555', 'currency_id' => null],
            ['country_name' => 'MADAGASCAR', 'country_code' => '120', 'currency_id' => null],
            ['country_name' => 'MALASIA', 'country_code' => '329', 'currency_id' => null],
            ['country_name' => 'MALAWI', 'country_code' => '115', 'currency_id' => null],
            ['country_name' => 'MALI', 'country_code' => '133', 'currency_id' => null],
            ['country_name' => 'MALTA', 'country_code' => '523', 'currency_id' => null],
            ['country_name' => 'MARRUECOS', 'country_code' => '128', 'currency_id' => null],
            ['country_name' => 'MARTINICA', 'country_code' => '250', 'currency_id' => null],
            ['country_name' => 'MAURICIO', 'country_code' => '119', 'currency_id' => null],
            ['country_name' => 'MAURITANIA', 'country_code' => '134', 'currency_id' => null],
            ['country_name' => 'MEXICO', 'country_code' => '216', 'currency_id' => null],
            ['country_name' => 'MICRONESIA', 'country_code' => '417', 'currency_id' => null],
            ['country_name' => 'MOLDOVA', 'country_code' => '556', 'currency_id' => null],
            ['country_name' => 'MONACO', 'country_code' => '535', 'currency_id' => null],
            ['country_name' => 'MONGOLIA', 'country_code' => '337', 'currency_id' => null],
            ['country_name' => 'MONSERRAT', 'country_code' => '252', 'currency_id' => null],
            ['country_name' => 'MONTENEGRO', 'country_code' => '561', 'currency_id' => null],
            ['country_name' => 'MOZAMBIQUE', 'country_code' => '121', 'currency_id' => null],
            ['country_name' => 'MYANMAR (EX BIR', 'country_code' => '326', 'currency_id' => null],
            ['country_name' => 'NAC.REPUTADA', 'country_code' => '998', 'currency_id' => null],
            ['country_name' => 'NAMIBIA', 'country_code' => '159', 'currency_id' => null],
            ['country_name' => 'NAURU', 'country_code' => '402', 'currency_id' => null],
            ['country_name' => 'NEPAL', 'country_code' => '320', 'currency_id' => null],
            ['country_name' => 'NICARAGUA', 'country_code' => '212', 'currency_id' => null],
            ['country_name' => 'NIGER', 'country_code' => '131', 'currency_id' => null],
            ['country_name' => 'NIGERIA', 'country_code' => '111', 'currency_id' => null],
            ['country_name' => 'NIUE', 'country_code' => '421', 'currency_id' => null],
            ['country_name' => 'NORUEGA', 'country_code' => '513', 'currency_id' => null],
            ['country_name' => 'NUEVA CALEDONIA', 'country_code' => '423', 'currency_id' => null],
            ['country_name' => 'NUEVA ZELANDIA', 'country_code' => '405', 'currency_id' => null],
            ['country_name' => 'OMAN', 'country_code' => '304', 'currency_id' => null],
            ['country_name' => 'ORIG.O DEST. NO', 'country_code' => '904', 'currency_id' => null],
            ['country_name' => 'OTROS(PAIS DESC', 'country_code' => '999', 'currency_id' => null],
            ['country_name' => 'PAKISTAN', 'country_code' => '324', 'currency_id' => null],
            ['country_name' => 'PANAMA', 'country_code' => '210', 'currency_id' => null],
            ['country_name' => 'PARAGUAY', 'country_code' => '222', 'currency_id' => null],
            ['country_name' => 'PERU', 'country_code' => '219', 'currency_id' => null],
            ['country_name' => 'PESCA EXTRA', 'country_code' => '903', 'currency_id' => null],
            ['country_name' => 'POLINESIA FRAN.', 'country_code' => '422', 'currency_id' => null],
            ['country_name' => 'POLONIA', 'country_code' => '528', 'currency_id' => null],
            ['country_name' => 'PORTUGAL', 'country_code' => '501', 'currency_id' => null],
            ['country_name' => 'PPUA.NVA.GUINEA', 'country_code' => '412', 'currency_id' => null],
            ['country_name' => 'PUERTO RICO', 'country_code' => '251', 'currency_id' => null],
            ['country_name' => 'QATAR', 'country_code' => '312', 'currency_id' => null],
            ['country_name' => 'RANCHO', 'country_code' => '900', 'currency_id' => null],
            ['country_name' => 'REINO UNIDO', 'country_code' => '510', 'currency_id' => null],
            ['country_name' => 'REP.CENT.AFRIC.', 'country_code' => '148', 'currency_id' => null],
            ['country_name' => 'REP.DEM. CONGO', 'country_code' => '143', 'currency_id' => null],
            ['country_name' => 'REP.DOMINICANA', 'country_code' => '206', 'currency_id' => null],
            ['country_name' => 'REP.ESLOVACA', 'country_code' => '545', 'currency_id' => null],
            ['country_name' => 'REPUBLICA CHECA', 'country_code' => '544', 'currency_id' => null],
            ['country_name' => 'REPUBLICA DE SE', 'country_code' => '546', 'currency_id' => null],
            ['country_name' => 'REPUBLICA DE YE', 'country_code' => '346', 'currency_id' => null],
            ['country_name' => 'RUMANIA', 'country_code' => '519', 'currency_id' => null],
            ['country_name' => 'RUSIA', 'country_code' => '562', 'currency_id' => null],
            ['country_name' => 'RWANDA', 'country_code' => '142', 'currency_id' => null],
            ['country_name' => 'SAHARAVI', 'country_code' => '165', 'currency_id' => null],
            ['country_name' => 'SAMOA OCC.', 'country_code' => '404', 'currency_id' => null],
            ['country_name' => 'SAN MARINO', 'country_code' => '536', 'currency_id' => null],
            ['country_name' => 'SANTA LUCIA(ISL', 'country_code' => '233', 'currency_id' => null],
            ['country_name' => 'SANTA SEDE', 'country_code' => '524', 'currency_id' => null],
            ['country_name' => 'SENEGAL', 'country_code' => '101', 'currency_id' => null],
            ['country_name' => 'SEYCHELLES', 'country_code' => '156', 'currency_id' => null],
            ['country_name' => 'SIERRA LEONA', 'country_code' => '105', 'currency_id' => null],
            ['country_name' => 'SINGAPUR', 'country_code' => '332', 'currency_id' => null],
            ['country_name' => 'SIRIA', 'country_code' => '310', 'currency_id' => null],
            ['country_name' => 'SNT.KIT & NEVIS', 'country_code' => '241', 'currency_id' => null],
            ['country_name' => 'SOMALIA', 'country_code' => '138', 'currency_id' => null],
            ['country_name' => 'SRI LANKA', 'country_code' => '314', 'currency_id' => null],
            ['country_name' => 'S.TOM.PRINCIPE', 'country_code' => '146', 'currency_id' => null],
            ['country_name' => 'SUDAFRICA', 'country_code' => '112', 'currency_id' => null],
            ['country_name' => 'SUDAN', 'country_code' => '123', 'currency_id' => null],
            ['country_name' => 'SUDAN DEL SUR', 'country_code' => '160', 'currency_id' => null],
            ['country_name' => 'SUECIA', 'country_code' => '511', 'currency_id' => null],
            ['country_name' => 'SUIZA', 'country_code' => '508', 'currency_id' => null],
            ['country_name' => 'SURINAM', 'country_code' => '235', 'currency_id' => null],
            ['country_name' => 'S.VTE.Y GRANAD.', 'country_code' => '234', 'currency_id' => null],
            ['country_name' => 'SWAZILANDIA', 'country_code' => '122', 'currency_id' => null],
            ['country_name' => 'TADJIKISTAN', 'country_code' => '557', 'currency_id' => null],
            ['country_name' => 'TAIWAN (FORMOSA', 'country_code' => '330', 'currency_id' => null],
            ['country_name' => 'TANZANIA', 'country_code' => '135', 'currency_id' => null],
            ['country_name' => 'TER.ESPAN.EN AF', 'country_code' => '152', 'currency_id' => null],
            ['country_name' => 'TER.HOLAN.EN AM', 'country_code' => '229', 'currency_id' => null],
            ['country_name' => 'TER.PORTUG.E/AS', 'country_code' => '343', 'currency_id' => null],
            ['country_name' => 'TERR.BRIT.EN AF', 'country_code' => '151', 'currency_id' => null],
            ['country_name' => 'TERR.BRIT.EN AM', 'country_code' => '227', 'currency_id' => null],
            ['country_name' => 'TERR.BRIT.EN AU', 'country_code' => '407', 'currency_id' => null],
            ['country_name' => 'TERR.D/DINAMARC', 'country_code' => '230', 'currency_id' => null],
            ['country_name' => 'TERR.FRAN.EN AF', 'country_code' => '153', 'currency_id' => null],
            ['country_name' => 'TERR.FRAN.EN AM', 'country_code' => '228', 'currency_id' => null],
            ['country_name' => 'TERR.FRAN.EN AU', 'country_code' => '408', 'currency_id' => null],
            ['country_name' => 'THAILANDIA', 'country_code' => '319', 'currency_id' => null],
            ['country_name' => 'TIMOR ORIENTAL', 'country_code' => '426', 'currency_id' => null],
            ['country_name' => 'T.NORTEAM.EN AU', 'country_code' => '409', 'currency_id' => null],
            ['country_name' => 'TOGO', 'country_code' => '109', 'currency_id' => null],
            ['country_name' => 'TRINID.Y TOBAGO', 'country_code' => '203', 'currency_id' => null],
            ['country_name' => 'TUNEZ', 'country_code' => '126', 'currency_id' => null],
            ['country_name' => 'TURCAS Y CAICOS', 'country_code' => '248', 'currency_id' => null],
            ['country_name' => 'TURKMENISTAN', 'country_code' => '558', 'currency_id' => null],
            ['country_name' => 'TURQUIA', 'country_code' => '522', 'currency_id' => null],
            ['country_name' => 'TUVALU', 'country_code' => '419', 'currency_id' => null],
            ['country_name' => 'UCRANIA', 'country_code' => '559', 'currency_id' => null],
            ['country_name' => 'UGANDA', 'country_code' => '136', 'currency_id' => null],
            ['country_name' => 'URUGUAY', 'country_code' => '223', 'currency_id' => null],
            ['country_name' => 'U.S.A.', 'country_code' => '225', 'currency_id' => null],
            ['country_name' => 'UZBEKISTAN', 'country_code' => '560', 'currency_id' => null],
            ['country_name' => 'VANUATU', 'country_code' => '415', 'currency_id' => null],
            ['country_name' => 'VENEZUELA', 'country_code' => '201', 'currency_id' => null],
            ['country_name' => 'VIETNAM', 'country_code' => '325', 'currency_id' => null],
            ['country_name' => 'ZAMBIA', 'country_code' => '117', 'currency_id' => null],
            ['country_name' => 'ZF.ARICA-ZF IND', 'country_code' => '910', 'currency_id' => null],
            ['country_name' => 'ZF.IQUIQUE', 'country_code' => '905', 'currency_id' => null],
            ['country_name' => 'ZF.PARENAS', 'country_code' => '907', 'currency_id' => null],
            ['country_name' => 'ZIMBABWE', 'country_code' => '116', 'currency_id' => null],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'country_name' => $country['country_name'],
                'country_code' => $country['country_code'],
                'currency_id' => $country['currency_id'],
                'is_active' => $country['is_active'] ?? true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
